### ISSUE TITLE
Could not find file '/etc/scrapeconfig.yml' but the file exists

### ISSUE THREAD

**Issue by ScrcufyTheJanitor** [stohrendorf/csv-prometheus-exporter#13]
I'm trying to use your csv-prometheus exporter to get csv-formatted metrics into a prometheus/alertmanager monitoring solution. However, when I run the docker command to start the exporter I get the following error:

`# docker run stohrendorf/csv-prometheus-exporter
2020-05-20 16:57:01.0187|INFO|csv_prometheus_exporter.Scraper.Scraper|Current threadpool min threads: worker=2, completionPort=2
2020-05-20 16:57:01.0401|INFO|csv_prometheus_exporter.Scraper.Scraper|New threadpool min threads: worker=128, completionPort=64

Unhandled Exception: System.IO.FileNotFoundException: Could not find file '/etc/scrapeconfig.yml'.
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func 2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize)
   at csv_prometheus_exporter.Scraper.Scraper.ReadCoreConfig(IList 1& readers) in /app/Scraper/Scraper.cs:line 30
   at csv_prometheus_exporter.Scraper.Scraper.Main(String[] args) in /app/Scraper/Scraper.cs:line 205`

But the file /etc/scrapeconfig.yml exists:

`# ls -l /etc/scrapeconfig.yml
-rwxr-xr-x 1 root root 1380 May 18 18:19 /etc/scrapeconfig.yml`

I'm not very familiar with Docker. I would appreciate any assistance you can provide.

**Comment by stohrendorf** [comment]
Bind your config into the container: https://docs.docker.com/storage/volumes/

**Comment by ScrcufyTheJanitor** [comment]
Thanks to your link and a bit of googling, I was able to get it to work with the following command:

`docker run -v /etc/scrapeconfig.yml:/etc/scrapeconfig.yml stohrendorf/csv-prometheus-exporter`
